set -U fish_color_host -o\x1ecyan
set -U fish_color_cwd_root red
set -U fish_pager_color_prefix cyan
set -U fish_color_cwd 008700
set -U fish_color_status red
set -U fish_color_param 00afff\x1ecyan
set -U fish_color_command 00d700
set -U fish_pager_color_progress cyan
set -U fish_color_normal 00d700
set -U fish_color_user -o\x1egreen
set -U fish_color_quote brown
set -U fish_color_history_current cyan
set -U fish_color_error red\x1e--bold
set -U fish_color_escape cyan
set -U fish_pager_color_description normal
set -U fish_color_redirection normal
set -U fish_pager_color_completion normal
set -U fish_color_operator cyan
set -U fish_color_comment red
set -U fish_color_match cyan
set -U fish_color_autosuggestion 555\x1eyellow
set -U fish_color_search_match purple
set -U fish_color_valid_path --underline
